language: node_js
node_js:
  - 12
script: ng build
branches:
  only:
    - development
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: dist/codeine-scene-gh-io
  target_branch: master
  on:
    branch: development